openapi: "3.0.0"

info:
  title: Spring Shop
  description: Shop API
  version: 1.0.0

paths:

  # Product
  /api/v1/products:
    $ref: './paths/products/products.yaml'
  /api/v1/products/{id}:
    $ref: './paths/products/products-id.yaml'

  # Category
  /api/v1/categories:
    $ref: './paths/categories.yaml'


components:
  schemas:

    # Product
    ProductCreateDto:
      $ref: './schemas/product/product-create.request.yaml'

    # Category
    CategoryCreateDto:
      $ref: './schemas/category/category-create.request.yaml'

