post:
  summary: Create a new product
  operationId: createProduct
  description: Create a new product
  tags:
    - Products
  requestBody:
    description: Product ID
    required: true
    content:
      application/json:
        schema:
          $ref: '../schemas/product/product-create.dto.yaml'
  responses:
    '201':
      description: CREATED
      content:
        application/json:
          schema:
            $ref: '../schemas/product/product.dto.yaml'
