type: object
properties:
  id:
    type: number
    positive: true
  name:
    type: string
  price:
    type: number
    format: double
  description:
    type: string
  categories:
    type: array
    items:
      $ref: './../category/category.response.yaml'
  createdAt:
    type: string
    format: date-time
  updatedAt:
    type: string
    format: date-time

required:
  - name
  - price
  - createdAt
  - updatedAt
