type: object
properties:
  name:
    type: string
  price:
    type: number
    format: double
  description:
    type: string
  categoryIds:
    type: array
    items:
      type: integer
      format: int64

required:
  - productName
  - price
  - categoryIds
