type: object
properties:
  name:
    type: string
  price:
    type: number
    format: double
  description:
    type: string
#  companySize:
#    type: string
#  companyType:
#    $ref: "./../company-type/company-type.yml"
#  locations:
#    type: array
#    items:
#      $ref: "./../company/company-location.yml"

required:
  - productName
  - price
