get:
  summary: Get all products
  operationId: getProducts
  description: Get all products
  tags:
    - Products
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../../schemas/product/product.response.yaml'

post:
  summary: Create a new product
  operationId: createProduct
  description: Create a new product
  tags:
    - Products
  requestBody:
    description: Product
    required: true
    content:
      application/json:
        schema:
          $ref: '../../schemas/product/product-create.request.yaml'
  responses:
    '201':
      description: CREATED
      content:
        application/json:
          schema:
            $ref: '../../schemas/product/product.response.yaml'
